version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies"
      - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
      # Sourcing nvm in the current shell session
      - export NVM_DIR="$HOME/.nvm"
      - '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"'  # Load nvm
      - '[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"'  # Load nvm bash completion
      - echo "Installing Node.js version 14"
      - nvm install 14  # You can change this to a specific version (e.g., 14.10.0)
      - nvm use 14  # Use Node.js version 14
      - node --version  # Verify Node.js version
      - npm --version  # Verify npm version
      - echo "Dependencies installed"

  build:
    commands:
      - echo "Running npm install"
      - npm install  # Install project dependencies
      - echo "Running npm run build"
      - npm run build  # Run the build script defined in package.json

  post_build:
    commands:
      - echo "Post-build tasks"
      - echo "Build completed successfully!"

artifacts:
  files:
    - '**/*'  # Include all files, you can adjust it to specific files/folders like dist/* if you want only build artifacts

cache:
  paths:
    - 'node_modules/**/*'  # Cache the node_modules directory to speed up future builds
